<?php

return [
    'version' => 'v1',
    'default_rate_limit' => env('CORE_API_RATE_LIMIT', '60,1'),
    'default_client_rate_limit' => (int) env('CORE_API_CLIENT_RATE_LIMIT', 120),
    'client_rate_window_seconds' => (int) env('CORE_API_CLIENT_RATE_WINDOW', 60),
    'per_app_rate_limits' => [],
    'per_ability_rate_limits' => [],
    'audit_logs' => [
        'enabled' => (bool) env('CORE_API_LOG_ENABLED', true),
        'retention_days' => (int) env('CORE_API_LOG_RETENTION_DAYS', 90),
        'keep_failed_requests_days' => (int) env('CORE_API_LOG_FAILED_RETENTION_DAYS', 180),
        'prune_chunk_size' => (int) env('CORE_API_LOG_PRUNE_CHUNK_SIZE', 1000),
        'keep_recent_minimum' => (int) env('CORE_API_LOG_KEEP_RECENT_MINIMUM', 1000),
        'prune_enabled' => (bool) env('CORE_API_LOG_PRUNE_ENABLED', true),
        'dry_run_default' => (bool) env('CORE_API_LOG_PRUNE_DRY_RUN', true),
    ],
    'expose_birth_date' => false,
    'expose_sensitive_fields' => false,
    'app_access_required' => true,
    'audit_sensitive_requests' => false,
    'directory_default_limit' => (int) env('CORE_API_DIRECTORY_DEFAULT_LIMIT', 25),
    'directory_max_limit' => (int) env('CORE_API_DIRECTORY_MAX_LIMIT', 100),

    'client_abilities' => [
        'read:users' => 'Read users',
        'read:students' => 'Read students',
        'read:lecturers' => 'Read lecturers',
        'read:employees' => 'Read employees',
        'read:study-programs' => 'Read study programs',
        'read:departments' => 'Read departments',
        'read:app-access' => 'Read app access',
        'read:leadership' => 'Read leadership',
        'verify:tu-portal-auth' => 'Verify TU portal password login without issuing tokens or sessions',
    ],

    'response_fields' => [
        'user' => [
            'id',
            'name',
            'email',
            'username',
            'identity_type',
            'identity_number',
            'active',
            'roles',
        ],
        'student' => [
            'id',
            'student_number',
            'name',
            'email',
            'status',
            'active',
            'enrolled_at',
            'study_program',
        ],
        'lecturer' => [
            'id',
            'lecturer_number',
            'name',
            'email',
            'phone',
            'active',
            'department',
            'study_program',
        ],
        'employee' => [
            'id',
            'employee_number',
            'name',
            'staff_type',
            'position_title',
            'email',
            'phone',
            'status',
            'department',
            'study_program',
        ],
    ],
];
